"""init

<<<<<<<< HEAD:alembic/versions/39683811261b_init.py
Revision ID: 39683811261b
Revises: 
Create Date: 2026-03-05 07:03:28.675465
========
Revision ID: 2bd614bbfbef
Revises: 
Create Date: 2026-03-19 16:29:01.140347
>>>>>>>> compare_tools:alembic/versions/2bd614bbfbef_init.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:alembic/versions/39683811261b_init.py
revision: str = '39683811261b'
========
revision: str = '2bd614bbfbef'
>>>>>>>> compare_tools:alembic/versions/2bd614bbfbef_init.py
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('zip_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('workspace_path', sa.String(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('completed_runs', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'FAILED', name='experimentstatus'), nullable=False),
    sa.Column('access_token_hash', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
<<<<<<<< HEAD:alembic/versions/39683811261b_init.py
========
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_config_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'FAILED', name='experimentstatus'), nullable=False),
    sa.Column('output_path', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_config_id'], ['run_configs.id'], ondelete='CASCADE'),
>>>>>>>> compare_tools:alembic/versions/2bd614bbfbef_init.py
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('run_configs')
    op.drop_table('experiments')
    op.drop_table('datasets')
    # ### end Alembic commands ###
