"""init

Revision ID: 5583527f1a64
Revises: 
Create Date: 2026-07-21 18:34:10.586961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5583527f1a64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('zip_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'READY', 'FAILED', name='datasetextractionstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('workspace_path', sa.String(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('completed_runs', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'FAILED', name='experimentstatus'), nullable=False),
    sa.Column('access_token_hash', sa.String(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('annotation_id', sa.String(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_config_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'FAILED', name='experimentstatus'), nullable=False),
    sa.Column('output_path', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_config_id'], ['run_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('run_configs')
    op.drop_table('annotations')
    op.drop_table('experiments')
    op.drop_table('datasets')
    # ### end Alembic commands ###
