STAIG_MANIFESTS = {
    "tool_id": "STAIG",
    "label": "STAIG",
    "description": "Self-supervised spatial domain identification with graph contrastive learning",
    "parameters": {
        "profile": {
            "type": "enum",
            "label": "Dataset profile",
            "options": [
                "DLPFC",
                "Human_Breast_Cancer",
                "Mouse_Olfactory",
                "human_placental_bed",
            ],
            "default": "DLPFC",
            "ui_group": "basic",
        },
        "num_clusters": {
            "type": "int",
            "label": "Number of clusters",
            "min": 3,
            "max": 30,
            "ui_group": "basic",
        },
        "num_epochs": {
            "type": "int",
            "label": "Training epochs",
            "min": 1,
            "max": 1000,
            "ui_group": "basic",
        },
        "k": {
            "type": "int",
            "label": "Graph neighborhood size (k)",
            "min": 5,
            "max": 150,
            "ui_group": "basic",
            "depends_on": {
                "profile": ["DLPFC"],
            },
        },
        "tau": {
            "type": "float",
            "label": "Contrastive temperature (tau)",
            "ui_group": "advanced",
        },
        "tau_decay": {
            "type": "float",
            "label": "Tau decay",
            "ui_group": "advanced",
            "depends_on": {
                "profile": ["Human_Breast_Cancer", "human_placental_bed"],
            },
        },
        "num_im_neigh": {
            "type": "int",
            "label": "Image neighbors",
            "ui_group": "advanced",
            "depends_on": {
                "profile": ["Human_Breast_Cancer", "human_placental_bed"],
            },
        },
        "learning_rate": {
            "type": "float",
            "label": "Learning rate",
            "ui_group": "advanced",
        },
        "seed": {
            "type": "int",
            "label": "Random seed",
            "ui_group": "advanced",
        },
        "num_layers": {
            "type": "int",
            "label": "GCN layers",
            "ui_group": "advanced",
        },
        "activation": {
            "type": "enum",
            "label": "Activation function",
            "options": ["relu", "prelu"],
            "ui_group": "advanced",
        },
    },
    "profiles": {
        "DLPFC": {
            "overrides": {
                "seed": 39788,
                "learning_rate": 0.0005,
                "num_clusters": 7,
                "num_epochs": 300,
                "tau": 35.0,
                "num_layers": 1,
                "k": 80,
                "activation": "prelu",
            },
            "internal_params": {
                "base_model": "GCNConv",
                "num_hidden": 64,
                "num_proj_hidden": 64,
                "drop_feature_rate_1": 0.1,
                "drop_feature_rate_2": 0.2,
                "weight_decay": 0.00001,
                "num_gene": 3000,
                "num_neigh": 5,
            },
        },
        "Mouse_Olfactory": {
            "overrides": {
                "seed": 39788,
                "learning_rate": 0.0005,
                "num_clusters": 7,
                "num_epochs": 340,
                "tau": 39.0,
                "num_layers": 1,
                "activation": "prelu",
            },
            "internal_params": {
                "base_model": "GCNConv",
                "num_hidden": 64,
                "num_proj_hidden": 64,
                "drop_feature_rate_1": 0.2,
                "drop_feature_rate_2": 0.2,
                "weight_decay": 0.00001,
                "num_gene": 3000,
                "num_neigh": 5,
            },
        },
        "Human_Breast_Cancer": {
            "overrides": {
                "seed": 39788,
                "learning_rate": 0.0005,
                "num_clusters": 20,
                "num_epochs": 580,
                "tau": 3.0,
                "tau_decay": 0.0,
                "num_layers": 2,
                "num_im_neigh": 2,
                "activation": "prelu",
            },
            "internal_params": {
                "base_model": "GCNConv",
                "num_hidden": 64,
                "num_proj_hidden": 64,
                "drop_edge_rate_1": 0.1,
                "drop_edge_rate_2": 0.3,
                "drop_feature_rate_1": 0.1,
                "drop_feature_rate_2": 0.2,
                "weight_decay": 0.00001,
                "num_gene": 3000,
                "num_neigh": 5,
            },
        },
        "human_placental_bed": {
            "overrides": {
                "seed": 36666,
                "learning_rate": 0.0005,
                "num_clusters": 10,
                "num_epochs": 10,
                "tau": 17.0,
                "tau_decay": 0.0,
                "num_layers": 1,
                "num_im_neigh": 2,
                "activation": "prelu",
            },
            "internal_params": {
                "base_model": "GCNConv",
                "num_hidden": 64,
                "num_proj_hidden": 64,
                "drop_edge_rate_1": 0.2,
                "drop_edge_rate_2": 0.3,
                "drop_feature_rate_1": 0.2,
                "drop_feature_rate_2": 0.2,
                "weight_decay": 0.00001,
                "num_gene": 1942,
                "num_neigh": 5,
            },
        },
    },
}